# Lecture 2

## Loops

In [1]:
word = 'oxygen'

In [6]:
print(word[0])
print(word[1])
print(word[2])
print(word[3])
print(word[4])

o
x
y
g
e


In [8]:
word = 'the'
for char in word: # use meaningful names for variables
    print(char)

t
h
e


In [12]:
for i in range(5, 10, 2): # start at 5, go up to 10, in increments of 2
    print(i)

5
7
9


In [23]:
result = 1
exponential = 3
x = 5
for number in range(0, exponential):
    result = result * x
print(result)

125


## Lists

In [24]:
mylist = [1, 3, 5, 7]
print(mylist)

[1, 3, 5, 7]


In [25]:
mylist[0]

1

In [26]:
mylist[-1]

7

In [27]:
for i in mylist:
    print(i)

1
3
5
7


In [28]:
names = ['Maria', 'Alice', 'James']

In [29]:
names

['Maria', 'Alice', 'James']

In [30]:
names[0] = 'Jake' # reassign

In [31]:
names

['Jake', 'Alice', 'James']

In [32]:
name = 'Jake'

In [34]:
name[0] = 'U' # strings are immutable, but lists are not

TypeError: 'str' object does not support item assignment

In [58]:
x = [1, 2, 3]

In [59]:
y = list(x) # copy of x list

In [60]:
y

[1, 2, 3]

In [61]:
x[0] = 'Darwin'

In [62]:
x

['Darwin', 2, 3]

In [63]:
y # assigned list(x) to y previously so if you modify x then you don't modify y

[1, 2, 3]

In [64]:
x = ['Darwin', 1, 3.0] # mix types

In [65]:
x = [['pepper', 'onion'],['bread', 'pasta'],['apple']] # lists of lists

In [67]:
x[0] # accesses the first item (first list)

['pepper', 'onion']

In [69]:
x[0][1] # accesses second item in the first list

'onion'

In [70]:
x = [['a', 'b'], 1, 2]

y = x
z = list(x)

In [71]:
x[0][0] = 'A'

In [72]:
x

[['A', 'b'], 1, 2]

In [73]:
y

[['A', 'b'], 1, 2]

In [74]:
z

[['A', 'b'], 1, 2]

In [75]:
x[1] = 5

In [76]:
x

[['A', 'b'], 5, 2]

In [77]:
y

[['A', 'b'], 5, 2]

In [78]:
z # still changed first list because python copied to list reference (shallow copy)

[['A', 'b'], 1, 2]

In [79]:
x.append(12) # add to list

In [80]:
x

[['A', 'b'], 5, 2, 12]

In [81]:
x.pop(0) # remove from list

['A', 'b']

In [82]:
x

[5, 2, 12]

In [87]:
x.reverse() # reverse list

In [88]:
x

[12, 2, 5]

In [89]:
x[0:2] # slice

[12, 2]

In [90]:
x[1:] # slice

[2, 5]

In [91]:
x = [1, 2, 4, 6, 6]

In [93]:
x[0:4:2] # slice, step interval

[1, 4]

In [94]:
x + y # concatenate list

[1, 2, 4, 6, 6, 12, 2, 5]

In [95]:
x * 2 # multiply list (repeats list x twice)

[1, 2, 4, 6, 6, 1, 2, 4, 6, 6]

In [99]:
string_for_slicing = 'Observation date: 25.02.2021'
list_for_slicing = [['flourine', 'F'],['chlorine', 'Cl'],['bromine', 'Br']]

In [102]:
print(list_for_slicing[0][0][-4:])

rine


In [104]:
string_for_slicing[-4:]

'2021'

In [113]:
print(list_for_slicing[1][0][-4:])

rine


In [117]:
for i in range(len(list_for_slicing)):
    print(list_for_slicing[i][0][-4:])

rine
rine
mine


## If statements

In [121]:
num = 37

if num >= 100:
    print('number is greater than or equal to 100')
elif num == 100:
    print('the number is 100')
else:
    print('the number is not greater than 100')
    

the number is not greater than 100


In [122]:
if num < 100 and num > 0:
    print('number between 0 and 100')
elif num > 100 or num < 0:
    print('the number is greater than 100 or less than 0')

number between 0 and 100


## Example with Inflammation data

In [123]:
import numpy as np

In [125]:
data = np.loadtxt(fname='data/inflammation-01.csv', delimiter=',') # load data

In [126]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [127]:
data.shape # check number of columns and rows

(60, 40)

In [130]:
data[0, :]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [132]:
data[0, :].shape # check number of rows match the original

(40,)

In [134]:
np.max(data), np.min(data)

(20.0, 0.0)

In [135]:
np.mean(data)

6.14875

In [136]:
np.max(data, axis=0).shape

(40,)

In [137]:
np.max(data, axis=0) 

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 19., 18., 17., 16., 15.,
       14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,
        1.])

In [139]:
np.max(data, axis=1).shape

(60,)

In [140]:
np.max(data, axis=1)

array([18., 18., 19., 17., 17., 18., 17., 20., 17., 18., 18., 18., 17.,
       16., 17., 18., 19., 19., 17., 19., 19., 16., 17., 15., 17., 17.,
       18., 17., 20., 17., 16., 19., 15., 15., 19., 17., 16., 17., 19.,
       16., 18., 19., 16., 19., 18., 16., 19., 15., 16., 18., 14., 20.,
       17., 15., 17., 16., 17., 19., 18., 18.])

In [142]:
max_inflammation_0 = np.max(data, axis=0)[0]
print(max_inflammation_0)
max_inflammation_20 = np.max(data, axis=0)[20]
print(max_inflammation_20)

0.0
20.0


In [143]:
if np.sum(np.min(data, axis=0)) == 0:
    print('Minima sum to zero')
elif max_inflammation_0 == 0 and max_inflammation_20 == 20:
    print('Check required')
else:
    print('Data look okay')

Check required


In [144]:
mylist = ['12'] 

if mylist:
    print('mylist is True') # test if condition is true/false

mylist is True


In [147]:
mylist = [] 

if not mylist:
    print('mylist is False') # test if condition is true/false

mylist is False


In [157]:
filenames = ['inflammation-01.csv', 'inflammation-02.csv', 'inflammation-03.csv', 'inflammation-04.csv', 'inflammation-05.csv', 'small-01.csv', 'small-02.csv', 'small-03.csv', 'src.py']

inflammation_data = []
small_data = []
other_data = []

for fname in filenames:
    if fname.startswith('inflamm'):
        inflammation_data.append(fname)
    elif fname.startswith('small'):
        small_data.append(fname)
    else:
        other_data.append(fname)
print(inflammation_data)
print(small_data)
print(other_data)

['inflammation-01.csv', 'inflammation-02.csv', 'inflammation-03.csv', 'inflammation-04.csv', 'inflammation-05.csv']
['small-01.csv', 'small-02.csv', 'small-03.csv']
['src.py']


## Functions

In [180]:
def fahr_to_celsius(temp):
    """
    Converts the temperature in fahr. to celsius. 
    
    :param temp: float, a temperature in fahr.
    
    Example
    -------
    .......
    """
    temp_celsius = ((temp - 32) * (5/9))
    return temp_celsius

def celsius_to_kelvin(temp_c):
    temp_k = temp_c + 273.15
    return temp_k

def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k

In [181]:
help(fahr_to_celsius)

Help on function fahr_to_celsius in module __main__:

fahr_to_celsius(temp)
    Converts the temperature in fahr. to celsius. 
    
    :param temp: float, a temperature in fahr.
    
    Example
    -------
    .......



In [160]:
fahr_to_celsius(32) # call function for input argument 32

0.0

In [161]:
fahr_to_celsius(212)

100.0

In [168]:
celsius_to_kelvin(0.)

TypeError: 'float' object is not callable

In [171]:
fahr_to_kelvin(212)

373.15

In [174]:
def sanity_check(data): # Create function from previous example above

    max_inflammation_0 = np.max(data, axis=0)[0]
    max_inflammation_20 = np.max(data, axis=0)[20]
    
    if np.sum(np.min(data, axis=0)) == 0:
        print('Minima sum to zero')
    elif max_inflammation_0 == 0 and max_inflammation_20 == 20:
        print('Check required')
    else:
        print('Data look okay')
    

In [173]:
sanity_check(data)

Check required


### Positional and keyword arguments
* look into this more but this is basically how you define arguments in function

In [182]:
data.shape

(60, 40)

In [183]:
def offset_mean(data, target_mean_value):
    
    return (data - np.mean(data)) + target_mean_value

In [184]:
offset_mean(data, 2.0)

array([[-4.14875, -4.14875, -3.14875, ..., -1.14875, -4.14875, -4.14875],
       [-4.14875, -3.14875, -2.14875, ..., -3.14875, -4.14875, -3.14875],
       [-4.14875, -3.14875, -3.14875, ..., -2.14875, -3.14875, -3.14875],
       ...,
       [-4.14875, -3.14875, -3.14875, ..., -3.14875, -3.14875, -3.14875],
       [-4.14875, -4.14875, -4.14875, ..., -4.14875, -2.14875, -4.14875],
       [-4.14875, -4.14875, -3.14875, ..., -3.14875, -3.14875, -4.14875]])

### Testing

In [185]:
test_data = np.zeros((3, 3)) # for testing, define matrix (3 x 3 of zeros)

In [186]:
test_data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [188]:
offset_mean(test_data, 3) # test function with your test data

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [191]:
number = 10

assert number == 12 # test value is as expected

AssertionError: 

In [194]:
def test_offset_mean(target_value):
    
    test_data = np.zeros((3,3))
    
    mydata = offset_mean(test_data, target_value)
    
    assert mydata [0, 0] == target_value
    
    print('Data passed')

In [195]:
test_offset_mean(4)

Data passed


In [196]:
patient_max = np.max(data, axis=1)

In [197]:
assert patient_max.shape == (60, )
assert patient_max.dtype == 'float32'

AssertionError: 

### Errors and exceptions

In [200]:
def favourite_ice_cream():
    ice_creams = ['vanilla', 'chocolate', 'lemon']
    print(ice_creams[3]) # asking for 4th item in list of 3
    
favourite_ice_cream()    

IndexError: list index out of range

In [201]:
def some_function():
    message = 'hello'
    print(message)
       return message # indentation error

IndentationError: unexpected indent (<ipython-input-201-3111f4a255c8>, line 4)

In [202]:
def some_function():
    message = 'hello'
    print message # missing () after print
    return message

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(message)? (<ipython-input-202-0d6faabcfbd1>, line 3)

In [203]:
def some_function() # missing :
    message = 'hello'
    print (message)
    return message

SyntaxError: invalid syntax (<ipython-input-203-99cc736c5d9c>, line 1)

In [204]:
hello # cannot just call variable without defining

NameError: name 'hello' is not defined

In [208]:
'hello' # can call string

'hello'

In [206]:
greetings = 'hello'

In [207]:
gretings # spelling error

NameError: name 'gretings' is not defined

In [209]:
for number in range(10):
    count = count + number # calling count without initializing count 
    
print('Count=', count)    

NameError: name 'count' is not defined

In [210]:
numbers = [1, 2, 3, 4]

numbers[0]

1

In [211]:
numbers[7] # trying request 8th item in list of 4

IndexError: list index out of range

In [212]:
data = np.loadtxt(fname='inflammation.csv', delimiter=',') #wrong file path

OSError: inflammation.csv not found.

### Magic commands from Jupyter 

In [217]:
%%writefile myfile.txt # create file in working directory and write string
'Hello'

Overwriting myfile.txt


In [218]:
myfile = open('myfile.txt', 'r') # open in read mode
hello = myfile.read()

In [219]:
hello

"'Hello'\n"

### Lists, tuples, and dictionaries

In [220]:
mylist = [1, 3, 4] # lists are immutable
mylist[0] = 'Darwin'

mylist

['Darwin', 3, 4]

In [221]:
mytuple = (1, 3, 4) # tuples are immutable
mytuple[1] = 'Darwin'

TypeError: 'tuple' object does not support item assignment

In [222]:
mydict = {'one': 'monday', 'two': 'tuesday'}

mydict['one']

'monday'

In [225]:
mydict.keys()

dict_keys(['one', 'two'])

In [226]:
mydict.items()

dict_items([('one', 'monday'), ('two', 'tuesday')])

In [235]:
def print_message(day):
    messages = {'monday': 'just another manic monday', 
                'tuesday': 'finally tuesday', 
                'wednesday': 'today is wednesday',
                'thursday': 'almost at the end', 
                'friday': "friday I'm in love"}
    
    print(messages[day])
    
def print_monday_message():
    print_message('monday')
    
print_monday_message()    

just another manic monday


In [237]:
x = 1

assert x == 0, 'x is not zero' # error message with assert

AssertionError: x is not zero

In [241]:
x = 1.2

assert np.isclose(x, 1.234, rtol=1e-04), 'x is not as expected' # can set value and set tolerance

AssertionError: x is not as expected

In [ ]:
def is_overlapping(rect1, rect2):
    """
    Checks that two rectangles are overlapping
    
    :param rect1: coordinates of the first rectangle
    :param rect2: coordinates of the second rectangle
    
    """
    if 